//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityInfo
    {
        public int AI_ID { get; set; }
        public Nullable<int> AI_CI_ID { get; set; }
        public string AI_Price { get; set; }
        public Nullable<System.DateTime> AI_Starttime { get; set; }
        public Nullable<System.DateTime> AI_Endtime { get; set; }
        public Nullable<int> AI_IS { get; set; }
    }
}
