//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdministratorInfo
    {
        public int AI_ID { get; set; }
        public string AI_HImage { get; set; }
        public string AI_Num { get; set; }
        public string AI_LoginPwd { get; set; }
        public string AI_Name { get; set; }
        public string AI_Sex { get; set; }
        public string AI_IDCard { get; set; }
        public string AI_Alipay { get; set; }
        public string AI_Balance { get; set; }
        public Nullable<int> AI_Type { get; set; }
        public Nullable<System.DateTime> AI_Date { get; set; }
    }
}
