//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerInfo
    {
        public int BI_ID { get; set; }
        public string BI_HImage { get; set; }
        public string BI_Phone { get; set; }
        public string BI_NickName { get; set; }
        public string BI_LoginPwd { get; set; }
        public string BI_Name { get; set; }
        public string BI_IDCared { get; set; }
        public Nullable<int> BI_Sex { get; set; }
        public string BI_PayPwd { get; set; }
        public string BI_Balance { get; set; }
        public Nullable<System.DateTime> BI_Date { get; set; }
        public Nullable<int> BI_SumScore { get; set; }
    }
}
