//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommodityInfo
    {
        public int CI_ID { get; set; }
        public Nullable<int> CI_CTI_ID { get; set; }
        public Nullable<int> CI_SI_ID { get; set; }
        public string CI_Name { get; set; }
        public Nullable<System.DateTime> CI_CreateDate { get; set; }
        public Nullable<int> CI_Is { get; set; }
        public Nullable<int> CI_Num { get; set; }
        public Nullable<int> CI_SalesNum { get; set; }
        public string CI_Discount { get; set; }
        public string CI_Price { get; set; }
        public string CI_NowPrice { get; set; }
        public string CI_Url { get; set; }
        public Nullable<int> CI_Sendgoods { get; set; }
    }
}
