//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Express
    {
        public int Express_ID { get; set; }
        public string Express_Name { get; set; }
        public Nullable<int> Express_Expense { get; set; }
        public string Express_Image { get; set; }
        public string Express_Desc { get; set; }
    }
}
