//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class FootprintInfo
    {
        public int FI_ID { get; set; }
        public Nullable<int> FI_BI_ID { get; set; }
        public Nullable<int> FI_CI_ID { get; set; }
        public Nullable<System.DateTime> FI_Date { get; set; }
    }
}
