//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyAddressInfo
    {
        public int MAI_ID { get; set; }
        public Nullable<int> MAI_Type { get; set; }
        public Nullable<int> MAI_BI_ID { get; set; }
        public string MAI_Phone { get; set; }
        public string MAI_Province { get; set; }
        public string MAI_City { get; set; }
        public string MAI_County { get; set; }
        public string MAI_Town { get; set; }
        public string MAI_MinuteAddress { get; set; }
        public Nullable<int> MAI_IS { get; set; }
        public string MAI_Remark { get; set; }
        public string MAI_Name { get; set; }
    }
}
