//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFormInfo
    {
        public int OFI_ID { get; set; }
        public Nullable<int> OFI_CI_ID { get; set; }
        public Nullable<int> OFI_Number { get; set; }
        public Nullable<int> OFI_BI_ID { get; set; }
        public string OFI_Money { get; set; }
        public Nullable<int> OFI_States { get; set; }
        public Nullable<System.DateTime> OFI_CreateDate { get; set; }
        public Nullable<int> OFI_SAI_ID { get; set; }
        public string OFI_Address { get; set; }
        public Nullable<int> Express_ID { get; set; }
    }
}
