//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreInfo
    {
        public int SI_ID { get; set; }
        public Nullable<int> SI_AI_ID { get; set; }
        public Nullable<int> SI_STI_ID { get; set; }
        public string SI_Name { get; set; }
        public string SI_Logo { get; set; }
        public string SI_Intro { get; set; }
        public Nullable<System.DateTime> SI_CreateDate { get; set; }
        public string SI_Remark { get; set; }
    }
}
